[workspace]
resolver = "3"
members = ["crates/bitplane-core", "crates/bitplane-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-or-later"
authors = ["Denis Homolík"]

[workspace.dependencies]
bitplane-core = { path = "crates/bitplane-core" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
