// @ts-check

// The navigation is written out by hand rather than autogenerated: the shape of
// the docs is the thing under review, so it should be readable in one file
// instead of inferred from a directory listing and a pile of frontmatter.
//
// Two sidebars, one per navbar item. The reference is a thing you come back to
// and scan, the narrative docs are a thing you read once — mixing them puts a
// wall of command pages under whatever a first-time reader is trying to finish.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'install',
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/plane',
        'concepts/project',
        'concepts/member',
        'concepts/script',
        'concepts/ownership-boundary',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/run-a-task-across-repos',
        'guides/adopt-an-existing-checkout',
        'guides/per-project-scripts',
        'guides/recover-a-broken-plane',
      ],
    },
  ],

  reference: [
    'reference/global-flags',
    'reference/member-syntax',
    'reference/exit-codes',
    'reference/refusals-and-waivers',
    // Plane verbs are bare, project verbs are always prefixed. The split is
    // visible here, in the navigation, and not only in the prose (ADR-0006).
    {
      type: 'category',
      label: 'Plane commands',
      collapsed: false,
      items: [
        'reference/plane/create',
        'reference/plane/add',
        'reference/plane/rm',
        'reference/plane/destroy',
        'reference/plane/rename',
        'reference/plane/repair',
        'reference/plane/list',
        'reference/plane/show',
        'reference/plane/status',
        'reference/plane/run',
      ],
    },
    {
      type: 'category',
      label: 'Project commands',
      collapsed: false,
      items: [
        'reference/project/add',
        'reference/project/adopt',
        'reference/project/list',
        'reference/project/show',
        'reference/project/rename',
        'reference/project/rm',
        'reference/project/fetch',
      ],
    },
  ],
};

export default sidebars;
